#!/usr/bin/env python3
"""
Patch service type files to add ROS 2-style wrapper classes.
For services like SetBool and Trigger, this adds wrapper classes to __init__.py
that combine Request and Response classes.
"""
import os
import sys
import re

def find_service_pairs(srv_dir):
    """
    Find service Request/Response pairs in a srv directory.
    Returns a list of service base names (e.g., ['SetBool', 'Trigger']).
    """
    files = [f for f in os.listdir(srv_dir) if f.endswith('.py')]
    
    services = set()
    for filename in files:
        if filename.endswith('_Request.py'):
            service_name = filename.replace('_Request.py', '')
            response_file = f'{service_name}_Response.py'
            if response_file in files:
                services.add(service_name)
    
    return sorted(services)

def patch_service_init(srv_dir):
    """
    Add ROS 2-style wrapper classes to __init__.py for all service pairs.
    """
    init_file = os.path.join(srv_dir, '__init__.py')
    if not os.path.exists(init_file):
        print(f"[SKIP] {init_file}: file not found")
        return 0
    
    with open(init_file, 'r') as f:
        content = f.read()
    
    services = find_service_pairs(srv_dir)
    if not services:
        print(f"[SKIP] {srv_dir}: no service pairs found")
        return 0
    
    patched_count = 0
    additions = []
    
    for service_name in services:
        request_class = f'{service_name}_Request'
        response_class = f'{service_name}_Response'
        
        # Check if wrapper class already exists
        if f'class {service_name}:' in content or f'class {service_name}(' in content:
            print(f"[SKIP] {service_name}: wrapper class already exists")
            continue
        
        # Check if Request/Response are imported
        if f'import {request_class}' not in content and f'from .{request_class}' not in content:
            print(f"[SKIP] {service_name}: {request_class} not imported")
            continue
        
        # Create wrapper class
        wrapper_code = f'''
# ROS 2-style service wrapper for {service_name}
class {service_name}:
    """ROS 2-style service type for {service_name}."""
    Request = {request_class}
    Response = {response_class}
'''
        additions.append(wrapper_code)
        print(f"[PATCHED] {service_name}: added wrapper class")
        patched_count += 1
    
    if additions:
        # Append all wrapper classes to __init__.py
        with open(init_file, 'a') as f:
            f.write('\n# ROS 2-style service wrappers (auto-generated by patch_service_types.py)\n')
            for wrapper_code in additions:
                f.write(wrapper_code)
    
    return patched_count

def main():
    if len(sys.argv) < 2:
        print(f"Usage: {sys.argv[0]} <root_dir>")
        print(f"  Patches all srv/__init__.py files under <root_dir>/**/srv/")
        sys.exit(1)
    
    root_dir = sys.argv[1]
    if not os.path.isdir(root_dir):
        print(f"Error: {root_dir} is not a directory")
        sys.exit(1)
    
    total_patched = 0
    
    # Find all srv directories
    for dirpath, dirnames, filenames in os.walk(root_dir):
        if not dirpath.endswith('/srv'):
            continue
        
        print(f"\n[INFO] Processing {dirpath}")
        patched_count = patch_service_init(dirpath)
        total_patched += patched_count
    
    print(f"\n[DONE] Patched {total_patched} service wrapper classes")
    return 0

if __name__ == '__main__':
    sys.exit(main())
