#!/usr/bin/env python3
"""
Patch service type files to add ROS 2-style wrapper classes.
For services like CancelGoal, this adds a top-level CancelGoal class that wraps
CancelGoal_Request and CancelGoal_Response.
"""
import os
import sys
import re

def patch_service_file(service_file):
    """
    Add ROS 2-style wrapper class to a service file.
    E.g., add 'class CancelGoal' that references CancelGoal_Request, CancelGoal_Response.
    """
    with open(service_file, 'r') as f:
        content = f.read()
    
    # Extract service name from file path
    # e.g., /path/to/action_msgs/srv/CancelGoal.py -> CancelGoal
    service_name = os.path.basename(service_file).replace('.py', '')
    
    # Skip Request/Response files
    if service_name.endswith('_Request') or service_name.endswith('_Response'):
        return False
    
    # Check if wrapper class already exists
    if f'class {service_name}:' in content or f'class {service_name}(' in content:
        print(f"[SKIP] {service_file}: wrapper class already exists")
        return False
    
    # Check if required component classes exist
    request_class = f'{service_name}_Request'
    response_class = f'{service_name}_Response'
    
    if not (f'class {request_class}' in content):
        print(f"[SKIP] {service_file}: {request_class} not found")
        return False
    
    # Create wrapper class
    wrapper_code = f'''

# ROS 2-style service wrapper (auto-generated by patch_service_types.py)
class {service_name}:
    """ROS 2-style service type for {service_name}."""
    Request = {request_class}
    Response = {response_class}
'''
    
    # Append to file
    with open(service_file, 'a') as f:
        f.write(wrapper_code)
    
    print(f"[PATCHED] {service_file}: added {service_name} wrapper class")
    return True

def main():
    if len(sys.argv) < 2:
        print(f"Usage: {sys.argv[0]} <root_dir>")
        print(f"  Patches all srv .py files under <root_dir>/**/srv/")
        sys.exit(1)
    
    root_dir = sys.argv[1]
    if not os.path.isdir(root_dir):
        print(f"Error: {root_dir} is not a directory")
        sys.exit(1)
    
    patched_count = 0
    
    # Find all srv directories
    for dirpath, dirnames, filenames in os.walk(root_dir):
        if not dirpath.endswith('/srv'):
            continue
        
        # Find service .py files (not _*Wrapper.py, not __init__.py, not *_Request/*_Response)
        for filename in filenames:
            if not filename.endswith('.py'):
                continue
            if filename.startswith('_') or filename.startswith('lib') or filename == '__init__.py':
                continue
            if filename.endswith('_Request.py') or filename.endswith('_Response.py'):
                continue
            
            service_file = os.path.join(dirpath, filename)
            if patch_service_file(service_file):
                patched_count += 1
    
    print(f"\n[DONE] Patched {patched_count} service files")
    return 0 if patched_count > 0 else 1

if __name__ == '__main__':
    sys.exit(main())
